---

- name: Vytvoření uživatele
  hosts: all
  become: yes
  vars:
    username: "{{ user_input_name }}"
    password_plain: "{{ user_input_password }}"

  tasks:
    - name: Vytvoření uživatele {{ username }}
      ansible.builtin.user:
        name: "{{ username }}"
        comment: "Založeno přes Ansible"
        shell: /bin/bash
        groups: sudo
        append: yes
        create_home: yes
        password: "{{ password_plain | password_hash('sha512') }}"
