---
- name: Update Ubuntu system
  hosts: linux_servers
  become: yes
  tasks:

    - name: Update apt cache
      become: yes
      apt:
        update_cache: yes
        cache_valid_time: 3600

    - name: Upgrade all packages to the latest version
      become: yes
      apt:
        upgrade: dist

    - name: Remove unused packages
      become: yes
      apt:
        autoremove: yes
        purge: yes
