---
- name: Linux server system update
  hosts: linux_servers
  become: yes
  tasks:
    - name: Run update
      apt:
        update_cache: yes
      become: yes

    - name: Run upgrade
      apt:
        upgrade: dist
      become: yes
