---
- name: Aktualizace systému přes sudo
  hosts: raspberries
  become: yes  # spustí všechny úlohy s oprávněním root (sudo)
  tasks:
    - name: Spustit apt update
      apt:
        update_cache: yes
      become: yes

    - name: Spustit apt upgrade
      apt:
        upgrade: dist
      become: yes
